# Generated by Django 4.1.5 on 2023-01-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_first_name_myuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(null=True, upload_to='users_images/%Y/%m/'),
        ),
    ]
